### ISSUE TITLE
Problem in fragments

### ISSUE THREAD

**Issue by davilaerte** [llvieira/GHCli#8]
There was a problem in using fragments, to create interactive navbar.

**Comment by llvieira** [comment]
@davilaerte please, tell us more about the problem.

**Comment by GabrielSVinha** [comment]
@Luiz-FS, @llvieira, @davilaerte is this issues resolved?

**Comment by llvieira** [comment]
I think so.

**Comment by GabrielSVinha** [comment]
Closing
